Update github-actions-ec2.yml

diff --git a/.github/workflows/github-actions-ec2.yml b/.github/workflows/github-actions-ec2.yml
--- a/.github/workflows/github-actions-ec2.yml
+++ b/.github/workflows/github-actions-ec2.yml
@@ -37,18 +37,16 @@ test:
 
     - name: Test website availability
       run: |
-        DEPLOYED_URL="http://${{ secrets.HOST_DNS }}"
+        DEPLOYED_URL= ${{ secrets.HOST_DNS }}
         echo "Testing accessibility of $DEPLOYED_URL"
         HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -m 30 $DEPLOYED_URL)
-        [ $HTTP_STATUS -eq 200 ]
-        echo "Website is accessible. Test passed!"
 
-        # if [ $HTTP_STATUS -eq 200 ]; then
-        #  echo "Website is accessible. Test passed!"
-        # else
-        #  echo "Error: Website is not accessible. HTTP Status Code: $HTTP_STATUS"
-        #  exit 1
-        # fi
+        if [ $HTTP_STATUS -eq 200 ]; then
+          echo "Website is accessible. Test passed!"
+        else
+          echo "Error: Website is not accessible. HTTP Status Code: $HTTP_STATUS"
+          exit 1
+        fi
   deploy:
     name: Deploy to EC2 on master branch push
     runs-on: ubuntu-latest
